// Mocks generated by Mockito from annotations
// in study_docs/test/features/documents/domain/add_document_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:study_docs/features/documents/domain/entities/study_document.dart'
    as _i4;
import 'package:study_docs/features/documents/domain/repositories/documents_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DocumentsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentsRepository extends _i1.Mock
    implements _i2.DocumentsRepository {
  MockDocumentsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> add(_i4.StudyDocument? doc) => (super.noSuchMethod(
    Invocation.method(#add, [doc]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> update(_i4.StudyDocument? doc) => (super.noSuchMethod(
    Invocation.method(#update, [doc]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? id) => (super.noSuchMethod(
    Invocation.method(#delete, [id]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.StudyDocument?> getById(String? id) => (super.noSuchMethod(
    Invocation.method(#getById, [id]),
    returnValue: _i3.Future<_i4.StudyDocument?>.value(),
  ) as _i3.Future<_i4.StudyDocument?>);

  @override
  _i3.Future<List<_i4.StudyDocument>> search({
    String? keyword,
    _i4.DocumentType? type,
    String? course,
  }) => (super.noSuchMethod(
    Invocation.method(#search, [], {
      #keyword: keyword,
      #type: type,
      #course: course,
    }),
    returnValue: _i3.Future<List<_i4.StudyDocument>>.value(
      <_i4.StudyDocument>[],
    ),
  ) as _i3.Future<List<_i4.StudyDocument>>);

  @override
  _i3.Future<List<_i4.StudyDocument>> getAll() => (super.noSuchMethod(
    Invocation.method(#getAll, []),
    returnValue: _i3.Future<List<_i4.StudyDocument>>.value(
      <_i4.StudyDocument>[],
    ),
  ) as _i3.Future<List<_i4.StudyDocument>>);
}
